version: '3.8'

services:
  django:
    build:
      context: .
    ports:
      - "8080-8090:8000"
    volumes:
      - .:/app
      - app_data:/app/data
    command: python manage.py runserver 0.0.0.0:8000
    scale: 2

volumes:
  app_data:
